// Auto-generated from hover-texts.txt
// Edit hover-texts.txt and regenerate via script.

window.MEDIA_HOVER = [
  { "categoryId": "arkhe-project", "file": "1x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "20.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "27.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "29.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "arzu.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "arzu5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "arzu6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "b1x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "b5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "b6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "bi3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "bi5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "bi6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "e1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "e5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "e6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "k1son.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "k5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "k6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "m1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "m5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "m6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "nöroson.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "r1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "r5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "r6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "rö3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "rö5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "rö6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "si1x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "si5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "si6x1.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "t2.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "t5x3.jpg", "text": "poster" },
  { "categoryId": "arkhe-project", "file": "t6x1.jpg", "text": "poster" },
  { "categoryId": "derschutze", "file": "34.png", "text": "poster" },
  { "categoryId": "derschutze", "file": "35.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "36.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "37.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "38.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "39.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "40.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "41.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "57.jpg", "text": "poster" },
  { "categoryId": "derschutze", "file": "59.jpg", "text": "poster" },
  { "categoryId": "derschutze", "file": "61.jpg", "text": "poster" },
  { "categoryId": "derschutze", "file": "62.jpg", "text": "poster" },
  { "categoryId": "derschutze", "file": "8.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "a1.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "a2.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "a3.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "a4.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "Artboard 11.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "Artboard 2.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "Artboard 3.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "flyer_newyork.jpg", "text": "flyer" },
  { "categoryId": "derschutze", "file": "gallery1.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "gallery2.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "Group 19.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "Group 20.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "Group 22.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "Group 25.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "Group 27.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "koiuzun.png", "text": "ad creative carousel" },
  { "categoryId": "derschutze", "file": "morocco1.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "morocco2.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "morocco3.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "news_gif_1.mp4", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "panbts2.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "pants.png", "text": "ad cread creativeative" },
  { "categoryId": "derschutze", "file": "pants1.png", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "spiderweb_newsletter.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "store_postsize.png", "text": "flyer" },
  { "categoryId": "derschutze", "file": "Artboard 1 copy 2.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "Artboard 1 copy 8.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "Artboard 1.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "available_news.jpg", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "available_newsletter_watch2.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "aziza_available_newsletter.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "email_blossom.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "email_newsletter.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "koi\u0026yasmin_newsletter.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "koi_newsletter1.png", "text": "newsletter" },
  { "categoryId": "derschutze", "file": "12.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "3.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "31.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "38.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "4.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "41.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "8.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "arabic_newspaper_baskı.jpg", "text": "printed newspaper" },
  { "categoryId": "derschutze", "file": "Group 19.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "Group 2.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "Group 20.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "Group 21.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "Group 22.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "Group 23.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "Group 24.png", "text": "sticker" },
  { "categoryId": "derschutze", "file": "poster_baskı_arabic_2.jpg", "text": "printed poster" },
  { "categoryId": "derschutze", "file": "poster_baskı_astro4_yeni.jpg", "text": "printed poster" },
  { "categoryId": "derschutze", "file": "poster_baskı_frog2.jpg", "text": "printed poster" },
  { "categoryId": "derschutze", "file": "poster_baskı_jazz2.jpg", "text": "printed poster" },
  { "categoryId": "derschutze", "file": "poster_baskı_yakuza3.jpg", "text": "printed poster" },
  { "categoryId": "derschutze", "file": "1.mp4", "text": "social media " },
  { "categoryId": "derschutze", "file": "2.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "27.mp4", "text": "website animation" },
  { "categoryId": "derschutze", "file": "3.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "33.mp4", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "34.mp4", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "35.mp4", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "36.mp4", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "4.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "5.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "52.mp4", "text": "ai video" },
  { "categoryId": "derschutze", "file": "53.mp4", "text": "ai video" },
  { "categoryId": "derschutze", "file": "54.mp4", "text": "ai video" },
  { "categoryId": "derschutze", "file": "57.mp4", "text": "website animation" },
  { "categoryId": "derschutze", "file": "63.mp4", "text": "video" },
  { "categoryId": "derschutze", "file": "64.mp4", "text": "video" },
  { "categoryId": "derschutze", "file": "9x16.mp4", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "andreas3.mp4", "text": "motion graphics" },
  { "categoryId": "derschutze", "file": "animasyon_sesli.mp4", "text": "animation" },
  { "categoryId": "derschutze", "file": "asansör sesli.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "BG.mp4", "text": "website bg" },
  { "categoryId": "derschutze", "file": "blossom.mp4", "text": "ad creative" },
  { "categoryId": "derschutze", "file": "Comp 1.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "Comp 2.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "Comp 3.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "Comp 4.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "Comp 5.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "deneme2.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "deneme4.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "insta_video.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "knit.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "logo çiçek.mp4", "text": "logo animation" },
  { "categoryId": "derschutze", "file": "Loop2_1.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "Morocco windows 2.mp4", "text": "website animation" },
  { "categoryId": "derschutze", "file": "retro1.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "retro2.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "retro3.mp4", "text": "social media" },
  { "categoryId": "derschutze", "file": "sakura_girl.mp4", "text": "logo animation" },
  { "categoryId": "derschutze", "file": "tracksuit1.mp4", "text": "ai video" },
  { "categoryId": "derschutze", "file": "tracksuit2.mp4", "text": "ai video" },
  { "categoryId": "derschutze", "file": "Tüm sahne2.mp4", "text": "social media" },
  { "categoryId": "kliik", "file": "1.png", "text": "social media" },
  { "categoryId": "kliik", "file": "2.png", "text": "social media" },
  { "categoryId": "kliik", "file": "2222.png", "text": "kidsandkods " },
  { "categoryId": "kliik", "file": "3.png", "text": "social media" },
  { "categoryId": "kliik", "file": "ahtapot_01.jpg", "text": "calipso" },
  { "categoryId": "kliik", "file": "ahtapot_02.jpg", "text": "calipso" },
  { "categoryId": "kliik", "file": "ahtapot_03.png", "text": "calipso" },
  { "categoryId": "kliik", "file": "Artboard 7 copy 3.png", "text": "ledwell" },
  { "categoryId": "kliik", "file": "Artboard 7 copy.png", "text": "ledwell" },
  { "categoryId": "kliik", "file": "Artboard 8 copy 2.png", "text": "ledwell" },
  { "categoryId": "kliik", "file": "Group 1.jpg", "text": "pandolce" },
  { "categoryId": "kliik", "file": "Group 2.jpg", "text": "pandolce" },
  { "categoryId": "kliik", "file": "Group 2.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 3.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 5-1.jpg", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 5-2.jpg", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 5.jpg", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 5.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 7 copy.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Group 7.png", "text": "lu gelato" },
  { "categoryId": "kliik", "file": "kabak tahin.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "kapı.png", "text": "lu gelato" },
  { "categoryId": "kliik", "file": "patelote.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "post.png", "text": "lu gelato" },
  { "categoryId": "kliik", "file": "sicilya.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "yorumlar.png", "text": "lugelato" },
  { "categoryId": "kliik", "file": "0322 (1).mp4", "text": "lugelato animation" },
  { "categoryId": "kliik", "file": "1.mp4", "text": "birkenstock ad " },
  { "categoryId": "kliik", "file": "2.mp4", "text": "birkenstock ad " },
  { "categoryId": "kliik", "file": "3.mp4", "text": "lugelato" },
  { "categoryId": "kliik", "file": "33.mp4", "text": "birkenstock ad " },
  { "categoryId": "kliik", "file": "7.mp4", "text": "kidsandkods" },
  { "categoryId": "kliik", "file": "8 mart video.mp4", "text": "lugelato" },
  { "categoryId": "kliik", "file": "8.mp4", "text": "kidsandkods" },
  { "categoryId": "kliik", "file": "altüst3.mp4", "text": "lugelato" },
  { "categoryId": "kliik", "file": "Artboard 1.mp4", "text": "lugelato" },
  { "categoryId": "kliik", "file": "cornetuzanma.mp4", "text": "lugelato" },
  { "categoryId": "kliik", "file": "denemedersi.mp4", "text": "kidsandkods" },
  { "categoryId": "kliik", "file": "kampanya.mp4", "text": "ledwell" },
  { "categoryId": "kliik", "file": "mavi kornet.mp4", "text": "lugelato" },
  { "categoryId": "kliik", "file": "tık.mp4", "text": "kidsandkods" },
  { "categoryId": "kliik", "file": "video.mp4", "text": "kliik ad creative" },
  { "categoryId": "nesin-koyu", "file": "de5x3.png", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "de6x1.jpg", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "deinsta.png", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "ga5x3.png", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "ga6x1.png", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "gainsta.png", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "pa1x1.jpeg", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "pa5x3.jpeg", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "pa6x1.jpeg", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "qu12.jpg", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "qu5x3_1.jpg", "text": "poster" },
  { "categoryId": "nesin-koyu", "file": "quİNSTA.jpg", "text": "poster" },
  { "categoryId": "personal", "file": "1.png", "text": "social media" },
  { "categoryId": "personal", "file": "15\u0027\u0027 Modyo Tv.mp4", "text": "TV ad" },
  { "categoryId": "personal", "file": "2.png", "text": "social media" },
  { "categoryId": "personal", "file": "3.png", "text": "social media" },
  { "categoryId": "personal", "file": "diabeticaliens_ecrin.mp4", "text": "game teaser" },
  { "categoryId": "personal", "file": "ege_uymaz_ortaköy_story.mp4", "text": "social media" },
  { "categoryId": "personal", "file": "hareketli_poster.mp4", "text": "TV ad" },
  { "categoryId": "personal", "file": "indirimweb_1920.mp4", "text": "WEB ad" },
  { "categoryId": "personal", "file": "karavana.mp4", "text": "social media" },
  { "categoryId": "personal", "file": "koel.mp4", "text": "social media" },
  { "categoryId": "personal", "file": "mindway.mp4", "text": "social media" },
  { "categoryId": "personal", "file": "turkishsoap.mp4", "text": "logo animation" },
  { "categoryId": "personal", "file": "video.mp4", "text": "social media" },
  { "categoryId": "personal", "file": "vreemu.mp4", "text": "social media" },
  { "categoryId": "personal", "file": "0322(1).mp4", "text": "Paribu Exhibition video" },
  { "categoryId": "personal", "file": "0322(2).mp4", "text": "app video" },
  { "categoryId": "personal", "file": "0322.mp4", "text": "Paribu Exhibition video 2" },
  { "categoryId": "personal", "file": "2.jpg", "text": "Paribu Exhibition " },
  { "categoryId": "personal", "file": "ameli2.png", "text": "Paribu Exhibition" },
  { "categoryId": "personal", "file": "içindek.jpg", "text": "Paribu Exhibition" },
  { "categoryId": "personal", "file": "sözlü2.png", "text": "Paribu Exhibition" },
  { "categoryId": "personal", "file": "1.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "2.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "3.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "4.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "Artboard 1.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "Artboard 1.png", "text": "social media" },
  { "categoryId": "personal", "file": "Artboard 2 copy 2.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "Untitled-1_01.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "Untitled-1_02.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "Untitled-1_03.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "Untitled-1_04.jpg", "text": "social media" },
  { "categoryId": "personal", "file": "video1.mp4", "text": "social media reel" },
  { "categoryId": "psikanaliz-dernegi", "file": "Artboard 1.png", "text": "poster" },
  { "categoryId": "psikanaliz-dernegi", "file": "Artboard 2.png", "text": "poster" },
  { "categoryId": "psikanaliz-dernegi", "file": "Artboard 3 copy.png", "text": "poster" },
  { "categoryId": "psikanaliz-dernegi", "file": "Artboard 3.png", "text": "poster" },
  { "categoryId": "psikanaliz-dernegi", "file": "Group 5-2.jpg", "text": "poster" }
];
